src/about/urls.py
from django.urls import include, path
from . import views

app_name = "about"

urlpatterns = [
    path('', views.about, name='about'),
]

src/api/urls.py
from django.urls import include, path
from . import views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

app_name = "api"

schema_view = get_schema_view(
   openapi.Info(
      title="PartsView API",
      default_version='v1',
      description="Electronic Parts Search Assistant - Public API",
      contact=openapi.Contact(email="parez.jakub@gmail.com"),
      license=openapi.License(name="MIT License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('docs', schema_view.with_ui('swagger', cache_timeout=0), name='docs'),
    #path('search/(?P<q>\w+)/', views.SearchView.as_view()),
    path('search/<str:q>/', views.SearchView.as_view())
]

src/basic/urls.py
from django.urls import include, path
from . import views

app_name = "basic"

urlpatterns = [
    path('', views.home, name='home'),
]

src/favourite/urls.py
from django.urls import include, path
from . import views

app_name = "favourite"

urlpatterns = [
    path('', views.favourite, name='favourite'),
]

src/history/urls.py
from django.urls import include, path
from . import views

app_name = "history"

urlpatterns = [
    path('', views.history, name='history'),
]

src/parts_view/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (
handler400, handler403, handler404, handler500
 )
 
from basic import views as basic_views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

import debug_toolbar

from django.views.generic.base import RedirectView


favicon_view = RedirectView.as_view(url='/static/favicon/favicon.ico', permanent=True)
favicon_view = RedirectView.as_view(url='/static/js/fa.js', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('login/', basic_views.login, name='login'),
    path('register/', basic_views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': '/'}, name='logout'),
    
    path('about/', include('about.urls')),
    path('api/', include('api.urls')),
    path('history/', include('history.urls')),
    path('favourite/', include('favourite.urls')),
    path('part/<str:searched>/<str:part>', include('part.urls')),
    path('search/<str:part>', include('search.urls')),
    path('ajax/', include('ajax.urls')),
    
    path('', include('basic.urls')),

    path('__debug__/', include(debug_toolbar.urls)),
    
    re_path(r'^favicon\.ico$', favicon_view),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'basic.views.handler404'

src/basic/models.py
from django.db import models
from django.utils import timezone
from django.utils.timezone import now
from django.contrib.auth.models import User
from jsonfield import JSONField

class BasePart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(max_length=100)
    name_enc = models.CharField(default="", max_length=100)
    manuf = models.CharField(max_length=100)
    desc = models.CharField(max_length=200)
    pdf = models.CharField(max_length=200)
    octo = models.CharField(max_length=200)
    search = models.CharField(max_length=100)
    search_enc = models.CharField(default="", max_length=100)
    time = models.DateTimeField(default=now, editable=False)

    img_big = models.CharField(max_length=200)
    img_big2 = models.CharField(max_length=200)
    img_big3 = models.CharField(max_length=200)
    img_big4 = models.CharField(max_length=200)
    img_small = models.CharField(max_length=200)
    img_footprint = models.CharField(max_length=200)
    img_symbol = models.CharField(max_length=200)

    farnell_mnu = models.CharField(max_length=50)
    farnell_czk = models.CharField(max_length=50)
    mouser_mnu = models.CharField(max_length=50)
    mouser_eur = models.CharField(max_length=50)
    digikey_mnu = models.CharField(max_length=50)
    digikey_usd = models.CharField(max_length=50)

    specs = JSONField()

    class Meta:
        abstract = True

    def __str__(self):
        return self.name

class HistoryPart(BasePart):
    pass

class FavouritePart(BasePart):
    pass

src/basic/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login
from django.views.decorators.csrf import ensure_csrf_cookie

@ensure_csrf_cookie
def home(request):
    return render(request, 'basic/home.html')
    
def handler404(request, *args, **argv):
    response = render_to_response('basic/404.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response

def login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return render(request, 'basic/home.html')
        else:
            return render(request, 'basic/login.html', {'fail': 1})
    else:
        return render(request, 'basic/login.html', {'fail': 0})
        
        
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            auth_login(request, user)
            return render(request, 'basic/home.html')
        else:
            return render(request, 'basic/register.html', {'form': form, 'fail': 1})
    else:
        form = UserCreationForm()
    return render(request, 'basic/register.html', {'form': form, 'fail': 0})

src/basic/templates/basic/base.html
{% load staticfiles %}

<html lang="cs">
<head>
    <title>PartsView</title>
    <meta http-equiv="Content-Language" content="cs">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Jakub Pařez"> 
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-treeview.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
	
	<link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
	<link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
	<link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
	<link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
	<link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
	<link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
	<link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
	<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon.ico' %}"/>
	<link rel="manifest" href="{% static 'favicon/manifest.json' %}">
	<meta name="msapplication-TileColor" content="#ffffff' %}">
	<meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
	<meta name="theme-color" content="#ffffff' %}">


</head>

<body id="background-div">
    
    <div class="layer">

        <nav class="navbar navbar-dark navbar-expand-lg fixed-top" style="background-color:rgba(213,213,213, 0.5">
            <a class="navbar-brand" href="/about" >
            <img src="{% static 'img/logo.png' %}" width="50" height="50" onmouseover="this.src='{% static 'img/logo2.png' %}'" onmouseout="this.src='{% static 'img/logo.png' %}'" style="cursor: default;">
            </a><span style="opacity:0.85;color: black; cursor: default;font-family: 'SF Display'; font-weight: 600; font-size: 2.0em;" onclick="window.location.href='/about'">PartsView</span>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" style="margin-left: 30px" id="navbarSupportedContent">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'basic:home' %}">
                            <button type="button" class="btn btn-dark opacity2 nounderline" style="font-family: 'SF Text'; font-weight: 400;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);">
                                <i class="fa fa-search " aria-hidden="true"></i>
                                Find Part
                            </button>
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'history:history' %}">
                            <button type="button" class="btn btn-dark opacity2 nounderline" style="font-family: 'SF Text'; font-weight: 200;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);">
                                <i class="fa fa-history" aria-hidden="true"></i>
                               History
                            </button>
                        </a>
                    </li>
    				</b><li class="nav-item">
                        <a class="nav-link" href="{% url 'favourite:favourite' %}">
                            <button type="button" class="btn btn-dark opacity2 nounderline" style="font-family: 'SF Text'; font-weight: 200;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);">
                                <i class="fa fa-heart" aria-hidden="true"></i>
                                Favourite
                            </button>
                        </a>
                    </li>
                    {% endif %}    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'api:docs' %}">
                            <button type="button" class="btn btn-dark opacity2 nounderline" style="font-family: 'SF Text'; font-weight: 400;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);">
                                <i class="fa fa-code" aria-hidden="true"></i>
                                API
                            </button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://github.com/parezj/PartsView" target="_blank">
                        <button type="button" class="btn btn-dark opacity2 nounderline" style="font-family: 'SF Text'; font-weight: 400;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);">
                            <i class="fa fa-github" aria-hidden="true"></i>
                            Source
                        </button>
                        </a>
                    </li>  
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about:about' %}">
                        <button type="button" class="btn btn-dark opacity2 nounderline" style="font-family: 'SF Text'; font-weight: 400;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);">
                            <i class="fa fa-question-circle" aria-hidden="true"></i>
                            About
                        </button>
                        </a>
                    </li>				
                    
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <div class="btn-group" role="group">
                                {% if user.is_superuser %}
                                    <button type="button" class="btn btn-info opacity2 nounderline" style="color: white;font-family: 'SF Text'; font-weight: 200;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);" onclick="location.href='/admin/'">
                                        <i class="fa fa-sliders" aria-hidden="true"></i>
                                        {{user.username}}
                                    </button>
                                 {% elif user.is_staff %}
                                    <button type="button" class="btn btn-warning nounderline" style="color: white; font-family: 'SF Text'; font-weight: 200;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);" disabled>
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                        {{user.username}}
                                    </button>
                                 {% else %}
                                    <button type="button" class="btn btn-success nounderline" style="color: white; font-family: 'SF Text'; font-weight: 200;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);" disabled>
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                        {{user.username}}
                                    </button>
                                 {% endif %}
                                             
                                 <button type="button" class="btn btn-danger opacity2 nounderline" style="font-family: 'SF Text'; font-weight: 200;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);" onclick="location.href='{% url 'logout' %}'">
                                    <i class="fa fa-power-off fa-lg" aria-hidden="true"></i>
                                    Odhlásit
                                 </button>                 
                            </div> 
                        </li>
                    {% else %}
    				    <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">
                            <button type="button" class="btn btn-info opacity2 nounderline" style="font-family: 'SF Text'; font-weight: 200;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);">
                                <i class="fa fa-user-plus" aria-hidden="true"></i>
                                Sign Up
                            </button>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">
                            <button type="button" class="btn btn-success opacity2 nounderline" style="font-family: 'SF Text'; font-weight: 200;box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 10px 20px 0 rgba(0, 0, 0, 0.25);">
                                <i class="fa fa-sign-in" aria-hidden="true"></i>
                                Log In
                            </button>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        
        <script src="{% static 'js/fa.js' %}"></script>
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap-treeview.js' %}"></script>
        <script src="{% static 'js/blob-util.js' %}"></script>
        <script src="{% static 'js/loadingoverlay.min.js' %}"></script>
        <script src="{% static 'js/sweetalert.min.js' %}"></script>
        <script src="{% static 'js/mediarecorder_polyfill.js' %}"></script>
        
        <script>
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent); // todo check
            var isFirefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1;
            var fa2 = "";
            if (isFirefox) fa2 = "fa-5x";
    
            var csrftoken = getCookie('csrftoken');
        </script>         
        
        <div class="main" style="margin-bottom: 20px">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</body>


</html>

src/basic/templates/basic/login.html
{% extends 'basic/base.html' %}

{% block content %}

<script> 
    var fail = {{fail}};
    if (fail == 1)
    {
        Swal.fire({ title: "Login failed", text: "Wrong username or password entered.", icon: 'error', confirmButtonText: 'OK'});
    }
    $(window).on('resize', function(){
        checkPosition4($(this).width());
    });
    
    $(window).on('load', function () {
        checkPosition4($(this).width());
    });

    function checkPosition4(winWidth)
    {
        if(winWidth < 767)
        {
            $("#form_login").css('left',"25%");
        } 
        else 
        {
            $("#form_login").css('left',"40%");
        }
    }
</script>

<div class="container">

  <form method="post" id="form_login" style="max-width: 330px;padding: 15px;margin: 0 auto;position: fixed;top: 40%; left: 40%;">
    {% csrf_token %}
    <!--<h2 class="form-signin-heading">Please sign in</h2>-->
    <label for="username" class="sr-only">Username</label>
    <input type="text" style="border:2;border-color:black" id="username" name="username" class="form-control" placeholder="Username" required autofocus>
    <label for="password" class="sr-only">Password</label>
    <input style="margin-top:5px;border:2;border-color:black" type="password" id="password" name="password" class="form-control" placeholder="Password" required>
    <button style="margin-top:5px" class="btn btn-lg btn-primary btn-block" type="submit">Log In</button>
  </form>

</div>
    
{% endblock %}

src/basic/templates/basic/register.html
{% extends 'basic/base.html' %}

{% block content %}

<script> 
    var fail = {{fail}};
    if (fail == 1)
    {
        Swal.fire({ title: "Registration failed", text: "Declared rules were not met.", icon: 'error', confirmButtonText: 'OK'});
    }
    $(window).on('resize', function(){
        checkPosition5($(this).width());
    });
    
    $(window).on('load', function () {
        checkPosition5($(this).width());
    });

    function checkPosition5(winWidth)
    {
        if(winWidth < 767)
        {
            $("#form_reg").css('left',"25%");
            $("#reg_tips").css('left',"12%");
        } 
        else 
        {
            $("#form_reg").css('left',"40%");
            $("#reg_tips").css('left',"35%");
        }
    }
</script>

  <form method="post" id="form_reg" style="max-width: 330px;padding: 15px;margin: 0 auto;position: fixed;top: 40%; left: 40%;">
    {% csrf_token %}
    <label for="username" class="sr-only">Username</label>
    <input type="text" style="border:2;border-color:black" id="username" name="username" class="form-control" placeholder="Username" required autofocus>
    <label for="password1" class="sr-only">Password</label>
    <input style="margin-top:5px;border:2;border-color:black" type="password" id="password1" name="password1" class="form-control" placeholder="Password" required>
	<label for="password2" class="sr-only">Password Repeat</label>
	<input style="margin-top:5px;border:2;border-color:black" type="password" id="password2" name="password2" class="form-control" placeholder="Password repeat" required>
    <button style="margin-top:5px" class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
</form>

<div id="reg_tips" style="margin: 0 auto;position: fixed;top: 70%; left: 35%;">
	<ul>
		<li><small style="color: white;text-shadow: 3px 2px 4px #000000;">Your password can't be too similar to your other personal information.</small></li>
		<li><small style="color: white;text-shadow: 3px 2px 4px #000000;">Your password must contain at least 8 characters.</small>
		</li><li><small style="color: white;text-shadow: 3px 2px 4px #000000;">Your password can't be a commonly used password.</small></li>
		<li>
			<small style="color: white;text-shadow: 3px 2px 4px #000000;">Your password can't be entirely numeric.</small></li></ul>
</div>


{% endblock %}

